<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '20e5b683b957de0f823a5a9aa17c1984' => $baseDir . '/src/extra.php',
);
